-- Aggregate functions in MySQL
SELECT * FROM STAFFS;
-- COUNT 
SELECT COUNT(*) AS TOTAL_STAFFS FROM STAFFS;

-- SUM
SELECT SUM(SALARY) AS TOTAL_SALARY_OF_EMPLOYESS FROM STAFFS;

-- AVERAGE 
SELECT AVG(salary) AS AVERAGE_SALARY_OF_EMPLOYEES FROM STAFFS;

-- MAXIMUM
SELECT  MAX(SALARY) AS HIGHEST_SALARY FROM STAFFS ;

-- MINIMUM
SELECT MIN(SALARY) AS HIGHEST_SALARY FROM STAFFS ;

-- GROUP BY CLAUSE 
SELECT department, MAX(salary) AS HIGHEST_SALARY FROM STAFFS GROUP BY department;

-- GROUP BY WITH HAVING CLAUSE 
SELECT department,MAX(salary)AS HIGHEST_SALARY FROM STAFFS GROUP BY department HAVING HIGHEST_SALARY>40000;



